### ISSUE TITLE
Unicode support?

### ISSUE THREAD

**Issue by hopewise** [rockswang/haxe-i18n#2]
Hi,

As I am trying to use unicode in stablexui, I tried to put the unicode character at strings.xml like this:

<t id="mega">&#2126</t>

but, in the widget, I just see &#2126, but not the character it self, any idea please?

**Comment by rockswang** [comment]
You can simply use native characters in &lt;your_locale&gt;/strings.xml, just make sure the file is encoded with UTF-8, UTF-8 encoding is while supported by Haxe compiler.

**Comment by hopewise** [comment]
Thanks, it worked .. :)

On Sat, Oct 5, 2013 at 11:33 AM, Rocks Wang notifications@github.comwrote:

> You can simply use native characters in /strings.xml, just make sure the
> file is encoded with UTF-8, UTF-8 encoding is while supported by Haxe
> compiler.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rockswang/haxe-i18n/issues/2#issuecomment-25744404
> .

## 

## 

## Kind Regards,

Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East
